version: '2'

service:
  nginx:
    image: nginx:1.13
    container_name: docker-laravel-nginx
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
  php:
    image: php:7.2-fpm
    container_name: docker-laravel-php
    ports:
      - "9000:9000"