version: '2'

services:
  web:
    image: nginx:1.13
    volumes:
      - ./html:/usr/share/nginx/html
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    command: [nginx-debug, '-g', 'daemon off;']